name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']  # Add more PHP versions if needed

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests with JUnit output
        run: |
          mkdir -p test-reports
          ./vendor/bin/phpunit --log-junit test-reports/junit.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports
          retention-days: 5

      - name: Show test summary
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: PHPUnit Tests
          path: test-reports/junit.xml
          reporter: java-junit
          fail-on-error: false
